--liquibase formatted sql

--changeset part1:create-storages
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition tableExists public.storages
CREATE TABLE public.storages
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id    BIGINT      NOT NULL,
    storage_name VARCHAR(20) NOT NULL,
    address      VARCHAR(40) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES public.clients (id) ON UPDATE CASCADE ON DELETE CASCADE
);
