--liquibase formatted sql

--changeset part1:create-product_owners
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition tableExists public.product_owners
CREATE TABLE public.product_owners
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id          BIGINT      NOT NULL,
    product_owner_name VARCHAR(20) NOT NULL,
    address            VARCHAR(40) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES public.clients (id) ON UPDATE CASCADE ON DELETE CASCADE
);
