--liquibase formatted sql

--changeset part1:create-waybills
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition tableExists public.waybills
CREATE TABLE public.waybills
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    distance    INTEGER NOT NULL,
    status      VARCHAR(25),
    start_date  DATE,
    end_date    DATE,
    invoice_id  BIGINT,
    car_id      BIGINT,
    verifier_id BIGINT,
    FOREIGN KEY (invoice_id) REFERENCES public.invoices (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES public.cars (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (verifier_id) REFERENCES public.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

--changeset part2:create-checkpoints
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition tableExists public.checkpoints
CREATE TABLE public.checkpoints
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address               VARCHAR(50),
    required_arrival_date DATE,
    checkpoint_date       DATE,
    waybill_id            BIGINT,
    FOREIGN KEY (waybill_id) REFERENCES public.waybills (id) ON UPDATE CASCADE ON DELETE CASCADE
);
