--liquibase formatted sql

--changeset part1:create-product_writeoffs
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition tableExists public.product_writeoffs
CREATE TABLE public.product_writeoffs
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount     INTEGER NOT NULL,
    status     VARCHAR(25),
    product_id BIGINT,
    creator_id BIGINT,
    FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (creator_id) REFERENCES public.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);
