app:
  info:
    applicationName: Cargo Tracking
    version: 0.0.1-SNAPSHOT
spring:
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cargotracking_db
    username: postgres
    password: adminpass
liquibase:
  change-log: classpath:/db.changelog/db.changelog-master.yaml
server:
  port: 8090