spring:
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cargotracking_db
    username: postgres
    password: adminpass
liquibase:
  changelog-file: classpath:/db/changelog/db.changelog-master.yaml generate-changelog
server:
  port: 8090
  address: localhost